name: Linux Tests

permissions:
  checks: write
  contents: read
  pull-requests: read

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  verify-alpine-installation:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/fanatixan/dotfiles/refs/heads/main/init-container.sh)"
      - run: test -f $HOME/.dotfiles/git/aliases
      - run: eza
