name: Run Tests on Various Platforms

permissions:
  checks: write
  contents: read
  pull-requests: read

on:
  push:
    paths:
      - home/**
      - .chezmoiroot
  pull_request:
    paths:
      - home/**
      - .chezmoiroot
  workflow_dispatch: {}

jobs:
  verify-alpine-installation:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
      - run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/fanatixan/dotfiles/refs/heads/main/init-container.sh)"
      - run: test -f $HOME/.dotfiles/git/aliases
      # - run: eza
  verify-ubuntu-installation:
    runs-on: ubuntu-latest
    steps:
      - run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/fanatixan/dotfiles/refs/heads/main/init-container.sh)"
      - run: test -f $HOME/.dotfiles/git/aliases
      # - run: eza
  verify-mac-installation:
    runs-on: macos-latest
    steps:
      - run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/fanatixan/dotfiles/refs/heads/main/init-container.sh)"
      - run: test -f $HOME/.dotfiles/git/aliases
      # - run: eza
